/**
 * Report Mapper (Pure Transformation Layer)
 *
 * Purpose:
 *   Converts domain objects (Dashboard DTOs, Insight DTOs, AI summaries, and Search DTOs)
 *   into immutable, generator-ready ReportDTOs.
 *
 * Strict Architectural Rules:
 *   - Static methods only.
 *   - Zero repositories, zero services, zero Prisma imports.
 *   - Pure functional transformation without side effects.
 */

import { ReportDTO, ReportType } from './report.types';
import { RepositoryInsight, ExecutiveSummary } from '../insights/insight.types';
import { AIResponse } from '../ai/ai.types';
import { UnifiedSearchResponse } from '../search/search.types';

export class ReportMapper {
  /**
   * Transforms heterogeneous engineering DTOs and AI summaries into an immutable ReportDTO.
   */
  static toReportDTO(input: {
    reportId: string;
    reportType: ReportType;
    title: string;
    subtitle?: string;
    insights?: ReadonlyArray<RepositoryInsight>;
    executiveSummary?: ExecutiveSummary;
    aiResponse?: AIResponse;
    searchData?: UnifiedSearchResponse;
  }): ReportDTO {
    const { reportId, reportType, title, subtitle, insights, executiveSummary, aiResponse, searchData } = input;
    const now = new Date().toISOString();

    const healthItems: Array<Record<string, unknown>> = [];
    const busFactorItems: Array<Record<string, unknown>> = [];
    const ownershipItems: Array<Record<string, unknown>> = [];
    const hotspotItems: Array<Record<string, unknown>> = [];
    const recommendationItems: Array<Record<string, unknown>> = [];

    if (insights && insights.length > 0) {
      for (const ins of insights) {
        healthItems.push({
          repositoryId: ins.repositoryId,
          repositoryName: ins.repositoryName,
          healthScore: ins.overallHealthScore,
          riskLevel: ins.overallRiskLevel,
          summary: ins.executiveSummary,
        });

        if (ins.busFactorInsight) {
          busFactorItems.push({
            repositoryName: ins.repositoryName,
            busFactorScore: ins.busFactorInsight.busFactorScore,
            riskLevel: ins.busFactorInsight.riskLevel,
            keyMaintainers: ins.busFactorInsight.siloedDevelopers,
            summary: ins.busFactorInsight.summary,
          });
        }

        if (ins.ownershipInsight) {
          for (const sil of ins.ownershipInsight.criticalSilos) {
            ownershipItems.push({
              repositoryName: ins.repositoryName,
              filePath: sil.filePath,
              primaryAuthor: sil.primaryOwner,
              ownershipPercentage: sil.ownershipPercentage,
              riskExplanation: sil.riskExplanation,
              riskLevel: ins.ownershipInsight.riskLevel,
            });
          }
        }

        if (ins.hotspotInsight) {
          for (const hot of ins.hotspotInsight.topCriticalHotspots) {
            hotspotItems.push({
              repositoryName: ins.repositoryName,
              filePath: hot.filePath,
              churnScore: hot.modificationsCount,
              churnRank: hot.churnRank,
              riskLevel: ins.hotspotInsight.riskLevel,
            });
          }
        }

        for (const rec of ins.consolidatedRecommendations) {
          recommendationItems.push({
            repositoryName: ins.repositoryName,
            title: rec.title,
            description: rec.description,
            riskLevel: rec.riskLevel,
          });
        }
      }
    } else if (searchData) {
      for (const h of searchData.health) {
        healthItems.push({ ...h });
      }
      for (const b of searchData.hotspots) {
        hotspotItems.push({ ...b });
      }
      for (const o of searchData.ownership) {
        ownershipItems.push({ ...o });
      }
      for (const r of searchData.insights) {
        recommendationItems.push({ ...r });
      }
    }

    const execSummaryText = executiveSummary
      ? executiveSummary.executiveHeadline
      : insights && insights.length > 0
        ? `Consolidated engineering health evaluation across ${insights.length} tracked workspace(s).`
        : 'Engineering intelligence report synthesized from system metrics and search indexing.';

    const aiSummaryText = aiResponse
      ? aiResponse.content
      : 'No AI executive briefing requested or generated for this report cycle.';

    return {
      reportId,
      reportType,
      title,
      subtitle,
      generatedAt: now,
      executiveSummary: execSummaryText,
      repositoryHealth: healthItems,
      busFactor: busFactorItems,
      ownership: ownershipItems,
      hotspots: hotspotItems,
      recommendations: recommendationItems,
      aiSummary: aiSummaryText,
      footer: 'Generated by GitPro Engineering Intelligence Platform • Confidential Engineering Report',
    };
  }
}
